#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Fri Aug 14 02:14:20 GMT 2026
android.enableAppCompileTimeRClass=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.usesSdkInManifest.disallowed=false
android.builtInKotlin=false
org.gradle.daemon.idletimeout=10800000
systemProp.user.language=en
systemProp.user.country=US
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
android.r8.optimizedResourceShrinking=false
kotlin.code.style=official
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.r8.strictFullModeForKeepRules=false
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
