package io.github.abdurazaaqmohammed.utils;

import android.content.Context;
import android.content.pm.PackageInfo;
import android.text.TextUtils;
import android.util.Base64;

import com.reandroid.arsc.chunk.xml.AndroidManifestBlock;

import net.lingala.zip4j.ZipFile;
import net.lingala.zip4j.model.FileHeader;

import org.apache.commons.io.FilenameUtils;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.cert.CertificateEncodingException;
import java.security.cert.X509Certificate;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

public class SignatureKillerUtil {

    public static final String KILLER_CLASS = "bin.mt.signature.KillerApplication";
    private static final String INJECTED_ASSET_DIR = "assets/SignatureKiller";
    private static final String[] ABIS = {"arm64-v8a", "armeabi-v7a", "x86_64", "x86"};


    public static File apply(Context context, File inputApk) throws Exception {
        PackageInfo info = context.getPackageManager().getPackageArchiveInfo(inputApk.getPath(), 0);
        if (info == null || TextUtils.isEmpty(info.packageName))
            throw new IOException("Could not determine package name of " + inputApk.getName());
        final String packageName = info.packageName;

        List<X509Certificate> certificates = null;
        IOException unverifiedFailure = null;
        try {
            certificates = CertUtil.getCertificatesUnverified(inputApk);
        } catch (IOException e) {
            unverifiedFailure = e;
        }
        if (certificates == null || certificates.isEmpty()) {
            try {
                certificates = CertUtil.getCertificates(inputApk);
            } catch (Exception e) {
                if (unverifiedFailure != null) e.addSuppressed(unverifiedFailure);
                throw new IOException("Could not extract the original signature from " + inputApk.getName(), e);
            }
        }
        if (certificates == null || certificates.isEmpty())
            throw new IOException("Could not extract the original signature from " + inputApk.getName());

        String signatureB64;
        try {
            signatureB64 = Base64.encodeToString(certificates.get(0).getEncoded(), Base64.NO_WRAP);
        } catch (CertificateEncodingException e) {
            throw new IOException(e);
        }

        File outFile = FileUtils.getUnusedFile(new File(inputApk.getParentFile(),
                FilenameUtils.getBaseName(inputApk.getName()) + "_killed.apk"));

        try (ZipFile zin = new ZipFile(inputApk)) {
            byte[] manifestBytes = null;
            String originalAppClass = null;
            int maxDexIndex = 0;
            for (FileHeader header : zin.getFileHeaders()) {
                String name = header.getFileName();
                if (header.isDirectory()) continue;
                if (name.equals("AndroidManifest.xml")) {
                    AndroidManifestBlock block;
                    try (InputStream is = zin.getInputStream(header)) {
                        block = AndroidManifestBlock.load(is);
                    }
                    originalAppClass = block.getApplicationClassName();
                    block.setApplicationClassName(KILLER_CLASS);
                    block.setExtractNativeLibs(true);
                    ByteArrayOutputStream bos = new ByteArrayOutputStream();
                    block.refreshFull();
                    block.writeBytes(bos);
                    manifestBytes = bos.toByteArray();
                } else if (name.matches("classes\\d*\\.dex")) {
                    String digits = name.substring("classes".length(), name.length() - ".dex".length());
                    int idx = digits.isEmpty() ? 1 : Integer.parseInt(digits);
                    if (idx > maxDexIndex) maxDexIndex = idx;
                }
            }
            if (manifestBytes == null) throw new IOException("No AndroidManifest.xml found");

            byte[] killerDex = readAll(context.getAssets().open("signature_killer/killer.dex"));

            Properties cfg = new Properties();
            cfg.setProperty("package", packageName);
            cfg.setProperty("signature", signatureB64);
            if (!TextUtils.isEmpty(originalAppClass) && !KILLER_CLASS.equals(originalAppClass))
                cfg.setProperty("appClass", originalAppClass);
            ByteArrayOutputStream cbos = new ByteArrayOutputStream();
            cfg.store(cbos, "Generated by MP Manager");

            File tmpDir = new File(context.getCacheDir(), "sigkill_" + System.currentTimeMillis());
            tmpDir.mkdirs();
            try {
                Set<String> skip = new HashSet<>();
                for (FileHeader header : zin.getFileHeaders()) {
                    String name = header.getFileName();
                    if (header.isDirectory()) continue;
                    if (isOldSignature(name)) skip.add(name);
                    else if (name.startsWith(INJECTED_ASSET_DIR + "/")) skip.add(name);
                    else if (name.startsWith("lib/") && name.endsWith("/libSignatureKiller.so")) skip.add(name);
                }
                Map<String, File> replacements = new LinkedHashMap<>();
                replacements.put("AndroidManifest.xml", writeTemp(tmpDir, "manifest.xml", manifestBytes));
                Map<String, File> additions = new LinkedHashMap<>();
                additions.put("classes" + (maxDexIndex + 1) + ".dex",
                        writeTemp(tmpDir, "killer.dex", killerDex));
                Map<String, Integer> methods = new HashMap<>();
                for (String abi : ABIS) {
                    InputStream is = openOrNull(context, "signature_killer/lib/" + abi + "/libSignatureKiller.so");
                    if (is == null) continue;
                    File soTmp = new File(tmpDir, "libSK-" + abi + ".so");
                    try (InputStream i2 = is; FileOutputStream fos = new FileOutputStream(soTmp)) {
                        byte[] buf = new byte[65536];
                        int n;
                        while ((n = i2.read(buf)) != -1) fos.write(buf, 0, n);
                    }
                    String entryName = "lib/" + abi + "/libSignatureKiller.so";
                    additions.put(entryName, soTmp);
                    methods.put(entryName, 0);
                }
                additions.put(INJECTED_ASSET_DIR + "/origin.apk", inputApk);
                additions.put(INJECTED_ASSET_DIR + "/config.properties",
                        writeTemp(tmpDir, "config.properties", cbos.toByteArray()));
                ApkZipAlignUtil.rebuildApk(inputApk, outFile, replacements, methods, additions, skip);
            } finally {
                deleteDir(tmpDir);
            }
        } catch (Exception e) {
            //noinspection ResultOfMethodCallIgnored
            outFile.delete();
            throw e;
        }
        return outFile;
    }

    private static File writeTemp(File dir, String name, byte[] data) throws IOException {
        File tmp = new File(dir, name);
        try (FileOutputStream fos = new FileOutputStream(tmp)) {
            fos.write(data);
        }
        return tmp;
    }

    private static void deleteDir(File dir) {
        if (dir == null || !dir.exists()) return;
        File[] files = dir.listFiles();
        if (files != null) {
            for (File f : files) {
                if (f.isDirectory()) deleteDir(f);
                else //noinspection ResultOfMethodCallIgnored
                    f.delete();
            }
        }
        //noinspection ResultOfMethodCallIgnored
        dir.delete();
    }

    private static boolean isOldSignature(String name) {
        String upper = name.toUpperCase(Locale.US);
        return upper.startsWith("META-INF/") &&
                (upper.endsWith(".RSA") || upper.endsWith(".DSA") || upper.endsWith(".EC")
                        || upper.endsWith(".SF") || upper.endsWith("MANIFEST.MF"));
    }

    private static InputStream openOrNull(Context context, String path) {
        try {
            return context.getAssets().open(path);
        } catch (IOException e) {
            return null;
        }
    }

    private static byte[] readAll(InputStream is) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte[] buf = new byte[1024 * 64];
        int len;
        while ((len = is.read(buf)) != -1) bos.write(buf, 0, len);
        is.close();
        return bos.toByteArray();
    }
}
